steps:
  - label: ":lint-roller: Linter"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Run Linter
      - eslint .
      - echo --- Success

  - label: ":typescript: Compile"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd src/
      - tsc
      - echo --- Success

  - label: ":pulumi: Preview AWS"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Executing Pulumi
      - cd infra/aws
      - pulumi preview --stack dev --non-interactive
      - echo --- Success

  - label: ":pulumi: Deploy AWS"
    branches: main
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Executing Pulumi
      - cd infra/aws
      - pulumi up --stack dev --non-interactive --yes
      - echo --- Success

  - wait

  - label: ":s3: Upload script to AWS"
    branches: main
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd infra/aws
      - export PULUMI_REST_API_URL="$(pulumi stack output url --stack dev)"
      - export AWS_S3_BUCKET="$(pulumi stack output bucketName --stack dev)"
      - cd ../../src/
      - cat enumerator.ts | envsubst '$$PULUMI_REST_API_URL' > new
      - mv new enumerator.ts
      - tsc
      - echo --- Uploading to AWS
      - aws s3 cp dist/enumerator.js "s3://$$AWS_S3_BUCKET/enumerator.js" --acl public-read
      - echo +++ Success
