steps:
  - label: lint
    if: build.branch != "main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Run Linter
      - eslint .
      - echo --- Success

steps:
  - label: build
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd src/
      - tsc
      - echo --- Success
