steps:
  - label: ":pipeline: Upload Dynamic Steps"
    command: .buildkite/pipeline.sh

  - label: ":lint-roller: Linter"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Run Linter
      - eslint .
      - echo --- Success

  - label: ":typescript: Compile"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd src/
      - tsc
      - echo --- Success

  - label: ":jest: Test Enumerator"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - jest
      - echo --- Success
    soft_fail:
      - exit_status: 1

  - label: ":pulumi: Preview AWS"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Executing Pulumi
      - cd infra/aws
      - pulumi preview --stack dev --non-interactive
      - echo --- Success

  - label: ":pulumi: Deploy AWS"
    key: deploy_pulumi
    branches: main
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Executing Pulumi
      - cd infra/aws
      - pulumi up --stack dev --non-interactive --yes
      - echo --- Success
