steps:
  - label: ":lint-roller: Linter"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Run Linter
      - eslint .
      - echo --- Success

  - label: ":typescript: Compile"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd src/
      - tsc
      - echo --- Success

  - label: ":pulumi: Preview AWS"
    branches: "!main"
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd infra/aws
      - pulumi preview --stack dev --non-interactive
      - echo --- Success

  - label: ":pulumi: Deploy AWS"
    branches: main
    command:
      - echo --- Load environment
      - direnv allow
      - eval "$(direnv export bash)"
      - echo +++ Build code
      - cd infra/aws
      - pulumi up --stack dev --non-interactive
      - echo --- Success
